name: CD Test

on:
  workflow_dispatch:  # لتشغيل الـ workflow يدويًا

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["test", "test2"]

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Run JavaScript
        run: |
          echo "Running JavaScript for service: ${{ matrix.service }}"
          node -e "console.log('Service name is: ${{ matrix.service }}')"
